project_id = "wfolueffkdzknuowwecf"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout-entreprise]
    verify_jwt = false
  [functions.create-payment]
    verify_jwt = false
  [functions.create-payment-lead]
    verify_jwt = false
  [functions.create-payment-talent]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.france-travail-offers]
    verify_jwt = false
  [functions.la-bonne-boite]
    verify_jwt = false
  [functions.rome-metier]
    verify_jwt = false
  [functions.send-welcome-entreprise]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.verify-diploma]
    verify_jwt = false
  [functions.send-notification]
    verify_jwt = false
  [functions.send-quote-pdf]
    verify_jwt = false
  [functions.chat-ai-assist]
    verify_jwt = false
  [functions.marche-du-travail]
    verify_jwt = false
  [functions.competences-rome]
    verify_jwt = false
  [functions.france-travail-formations]
    verify_jwt = false
  [functions.france-travail-agences]
    verify_jwt = false
